/* Presentation only. The existing journal, ledger, imports and backups remain authoritative. */
(() => {
  const icons={
    overview:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
    positions:'<path d="M4 20V10m8 10V4m8 16V7"/>',
    journal:'<rect x="5" y="3" width="15" height="18" rx="2"/><path d="M9 8h7M9 12h7M9 16h4M2 7h5M2 12h5M2 17h5"/>',
    screen:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',
    backup:'<path d="M12 3 3 7v5c0 5 9 9 9 9s9-4 9-9V7l-9-4Z"/><path d="m8 12 3 3 5-6"/>',
    settings:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="9" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="8" cy="18" r="2"/>',
    guide:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4m0 3h.01"/>',
    refresh:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 6a8 8 0 0 1 13 3M5 15a8 8 0 0 0 13 3"/>',
    plus:'<path d="M12 5v14M5 12h14"/>',
    arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
    close:'<path d="m6 6 12 12M6 18 18 6"/>',
    menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
    download:'<path d="M12 3v12m-5-5 5 5 5-5M4 15v5h16v-5"/>'
  };
  const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.overview}</svg>`;
  const routes={overview:['Overview','Your portfolio, in perspective.'],positions:['Positions','Monitor your hedge. Update your broker inputs.'],journal:['Trade journal','Every entry, rebalance, cover and recorded cost.'],screen:['ETF screener','Find candidates. Verify the inputs before acting.'],backup:['Backup & recovery','Keep your history safe and recoverable.'],settings:['Settings','Set the assumptions behind your screening and risk checks.'],guide:['Strategy guide','Understand the numbers behind the trade.']};
  const cardFor=id=>$(id).closest('.card');
  const cards={watch:cardFor('decisionCenter'),performance:cardFor('lifetimeSummary'),capital:cardFor('capitalSummary'),positions:cardFor('positions'),snapshot:cardFor('snapPair'),entry:cardFor('tp'),journal:cardFor('lots'),screen:cardFor('rows'),settings:cardFor('target'),backup:cardFor('localSafety')};
  const guide=[...document.querySelectorAll('body > .card')].find(c=>c.querySelector('h2')?.textContent.includes('How this trade'));
  const footer=[...document.querySelectorAll('body > .card')].at(-1);
  document.body.classList.add('workspace');
  const shell=document.createElement('div');shell.id='workspace';
  shell.innerHTML=`<a class="skip-link" href="#mainContent">Skip to content</a>
    <aside class="sidebar" id="sidebar"><a class="brand" href="#overview" aria-label="ETF Edge overview"><span class="brand-mark">${icon('positions')}</span><span>ETF<span class="brand-light">Edge</span><small>PORTFOLIO WORKSPACE</small></span></a>
    <div class="workspace-label"><span class="workspace-monogram">P</span><div>My portfolio<small>Relative value strategies</small></div><span class="workspace-dot"></span></div>
    <p class="nav-label">WORKSPACE</p><nav aria-label="Main navigation">${['overview','positions','journal','screen'].map(r=>`<a href="#${r}" data-route="${r}">${icon(r)}<span>${routes[r][0]}</span>${r==='positions'?'<span id="navPositionCount" class="nav-count">0</span>':''}</a>`).join('')}</nav>
    <p class="nav-label nav-second">MANAGE</p><nav aria-label="Portfolio tools">${['backup','settings','guide'].map(r=>`<a href="#${r}" data-route="${r}">${icon(r)}<span>${routes[r][0]}</span></a>`).join('')}</nav>
    <div class="sidebar-bottom"><a class="backup-prompt" href="#backup">${icon('backup')}<div><strong id="sidebarBackupTitle">Protect your journal</strong><small id="sidebarBackupText">Review backup status</small></div>${icon('arrow')}</a><div class="sidebar-foot"><span class="mini-mark">E</span><span>ETF Edge Finder<small>Personal workspace · v6.2</small></span></div></div></aside>
    <button class="nav-scrim" id="navScrim" aria-label="Close navigation" hidden></button>
    <div class="workspace-main"><header class="topbar"><div class="breadcrumb"><button class="icon-button mobile-toggle" id="menuToggle" aria-label="Open navigation" aria-expanded="false" aria-controls="sidebar">${icon('menu')}</button><span class="breadcrumb-root">Workspace</span><span class="breadcrumb-slash">/</span><span id="breadcrumbCurrent">Overview</span></div><div class="topbar-right"><span id="headerQuoteStatus" class="connection"><i></i>Loading quotes</span><span class="topbar-divider"></span><span class="profile-avatar" title="Personal portfolio">P</span></div></header>
    <main id="mainContent" tabindex="-1"><div class="page-heading"><div><div class="eyebrow" id="pageEyebrow">PORTFOLIO WORKSPACE</div><h1 id="pageTitle">Overview</h1><p id="pageSubtitle">Your portfolio, in perspective.</p></div><div class="page-actions"><button class="secondary refresh-button" data-refresh onclick="run()">${icon('refresh')}<span>Refresh prices</span></button><button id="newEntryButton" class="primary-button">${icon('plus')}Record activity</button></div></div>
    <div id="globalNotice"></div>
    ${Object.keys(routes).map(r=>`<section data-page="${r}" aria-label="${routes[r][0]}" ${r==='overview'?'':'hidden'}></section>`).join('')}
    <footer class="workspace-footer"><span>ETF Edge · Decision support for your recorded trades</span><span>Prices can be delayed. Confirm execution details with your broker.</span></footer></main></div>
    <dialog id="activityDialog" aria-labelledby="activityDialogTitle"><div class="dialog-heading"><div><span class="eyebrow">TRADE JOURNAL</span><h2 id="activityDialogTitle">Record activity</h2></div><button class="icon-button" id="closeActivity" aria-label="Close record activity">${icon('close')}</button></div><div class="segmented" role="tablist" aria-label="Activity type"><button role="tab" data-entry-tab="entry" aria-selected="true">Paired entry</button><button role="tab" data-entry-tab="adjustment" aria-selected="false">Rebalance / cost</button></div><div id="dialogForms"></div></dialog>
    <div class="toast" id="workspaceToast" role="status" hidden></div>`;
  document.body.prepend(shell);
  const page=r=>document.querySelector(`[data-page="${r}"]`);
  $('globalNotice').append($('storageWarning'));
  const hero=document.createElement('div');hero.className='portfolio-hero';hero.append($('lifetimeSummary'));page('overview').append(hero,cards.capital,cards.watch,cards.performance);
  page('positions').append(cards.positions,cards.snapshot);
  page('journal').append(cards.journal);
  page('screen').append(cards.screen);
  page('settings').append(cards.settings);
  page('backup').append(cards.backup);
  page('guide').append(guide,footer);
  $('dialogForms').append(cards.entry);cards.entry.querySelector('h2').remove();
  cards.entry.querySelector('.divider')?.remove();
  const forms=[...cards.entry.querySelectorAll('details')];forms.forEach((f,i)=>{f.open=true;f.dataset.entryPanel=i?'adjustment':'entry';f.querySelector('summary').hidden=true;f.hidden=!!i;});
  for(const node of [...document.body.children])if(node!==shell&&!['SCRIPT','STYLE','LINK'].includes(node.tagName))node.remove();
  cards.watch.querySelector('h2').textContent='Position watch';cards.watch.querySelector('.decisionHead .muted').textContent='Hedge balance, borrow conditions and next steps.';cards.watch.querySelector('[data-refresh]').remove();
  const watchLink=document.createElement('a');watchLink.href='#positions';watchLink.className='text-link';watchLink.innerHTML='View positions '+icon('arrow');cards.watch.querySelector('.decisionHead').append(watchLink);
  $('lifetimeTitle').textContent='Performance by pair';cards.performance.querySelector('p').textContent='Combined results include recorded rebalances and covers. Open and closed pairs stay in your history.';
  cards.positions.querySelector('h2').textContent='Open positions';cards.snapshot.querySelector('h2').textContent='Update broker snapshot';cards.journal.querySelector('h2').textContent='Activity ledger';cards.screen.querySelector('h2').textContent='Opportunity universe';cards.backup.querySelector('h2').textContent='Your data, protected';
  cards.performance.querySelector('thead tr').innerHTML='<th>Pair</th><th>Realized</th><th>Still open</th><th>Costs entered</th><th>Income entered</th><th>Combined result</th>';
  const tableTools=document.createElement('div');tableTools.className='table-tools';tableTools.innerHTML=`<label class="search-field">${icon('screen')}<input id="screenSearch" type="search" placeholder="Search ticker or underlying…" aria-label="Search ETF pairs"></label><label class="filter-field"><span>Show</span><select id="screenFilter"><option value="all">All pairs</option><option value="held">My positions</option><option value="research">Research list</option><option value="priority">Priority research</option><option value="watch">SpaceX watchlist</option></select></label><span class="table-count" id="screenResultCount"></span>`;cards.screen.querySelector('.wrap').before(tableTools);
  const journalTools=document.createElement('div');journalTools.className='table-tools';journalTools.innerHTML=`<label class="search-field">${icon('screen')}<input id="journalSearch" type="search" placeholder="Search your journal…" aria-label="Search journal"></label><button class="secondary" id="recordRebalance">${icon('plus')}Rebalance or cost</button><button class="secondary" onclick="downloadBackup()">${icon('download')}Export journal</button>`;cards.journal.querySelector('h2').after(journalTools);
  cards.journal.querySelectorAll('details').forEach(d=>d.open=true);
  const costField=$('costCategory').parentElement;
  const originalAdjChanged=adjActionChanged;adjActionChanged=function(){originalAdjChanged();costField.hidden=!['cost','income'].includes($('adjAction').value);};adjActionChanged();
  let currentPage='overview',toastTimer;
  function switchPage(){const route=location.hash.slice(1),r=routes[route]?route:'overview';currentPage=r;document.querySelectorAll('[data-page]').forEach(p=>p.hidden=p.dataset.page!==r);document.querySelectorAll('[data-route]').forEach(a=>{a.classList.toggle('active',a.dataset.route===r);if(a.dataset.route===r)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('pageTitle').textContent=routes[r][0];$('pageSubtitle').textContent=routes[r][1];$('breadcrumbCurrent').textContent=routes[r][0];$('pageEyebrow').textContent=r==='overview'?'YOUR INVESTING WORKSPACE':'PORTFOLIO WORKSPACE';document.title=routes[r][0]+' · ETF Edge';toggleMenu(false);window.scrollTo({top:0,behavior:'instant'});}
  function toggleMenu(open){document.body.classList.toggle('nav-open',open);$('menuToggle').setAttribute('aria-expanded',String(open));$('navScrim').hidden=!open;$('sidebar').inert=window.innerWidth<=720&&!open;}
  window.addEventListener('resize',()=>{if(window.innerWidth>720)toggleMenu(false);else $('sidebar').inert=!document.body.classList.contains('nav-open');});
  window.addEventListener('hashchange',switchPage);$('menuToggle').onclick=()=>toggleMenu(!document.body.classList.contains('nav-open'));$('navScrim').onclick=()=>toggleMenu(false);
  function selectEntryPanel(kind){forms.forEach(p=>p.hidden=p.dataset.entryPanel!==kind);document.querySelectorAll('[data-entry-tab]').forEach(b=>{const selected=b.dataset.entryTab===kind;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;});}
  function openActivity(kind='entry'){clearTradeForm();$('activityDialogTitle').textContent='Record activity';if(kind==='adjustment'){const held=allLedgers();if(held.length&&!held.some(p=>p.e===$('adjPair').value))$('adjPair').value=held[0].e;}selectEntryPanel(kind);if(!$('activityDialog').open)$('activityDialog').showModal();}
  $('newEntryButton').onclick=()=>openActivity();$('recordRebalance').onclick=()=>openActivity('adjustment');$('closeActivity').onclick=()=>$('activityDialog').close();
  document.querySelectorAll('[data-entry-tab]').forEach(b=>{b.onclick=()=>selectEntryPanel(b.dataset.entryTab);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const other=b.dataset.entryTab==='entry'?'adjustment':'entry';selectEntryPanel(other);document.querySelector(`[data-entry-tab="${other}"]`).focus();}};});
  const originalEdit=editTrade;editTrade=function(tid){openActivity('entry');originalEdit(tid);if(editingTradeId){$('activityDialogTitle').textContent='Correct entry fills';$('tradeWhen').disabled=true;$('tradeWhen').parentElement.hidden=true;}};
  const originalClear=clearTradeForm;clearTradeForm=function(){originalClear();$('tradeWhen').value='';$('tradeWhen').disabled=false;$('tradeWhen').parentElement.hidden=false;};
  $('activityDialog').addEventListener('close',()=>clearTradeForm());
  function signed(n,d=2){return Number.isFinite(n)?(n>0?'+':n<0?'−':'')+money(Math.abs(n),d):'—';}
  const color=n=>Number.isFinite(n)?n>=0?'positive':'negative':'muted';
  const avatar=(ticker,i=0)=>`<span class="ticker-avatar tint-${i%4}">${esc(ticker.slice(0,2))}</span>`;
  const originalLifetime=renderLifetime;
  renderLifetime=function(){
    originalLifetime();
    const list=PAIRS.map(p=>ledger(p.e)).filter(Boolean),has=list.length>0,complete=has&&list.every(p=>Number.isFinite(p.net)),sum=k=>list.reduce((s,p)=>s+p[k],0),net=complete?sum('net'):NaN,realized=has?sum('realized'):NaN,unreal=complete?sum('unreal'):NaN,costs=sum('costs'),income=sum('income'),hasCosts=adjustments.some(a=>a.action==='cost'),open=list.filter(p=>!p.closed),max=Math.max(1,...list.map(p=>Math.abs(p.net)||0));
    $('lifetimeSummary').className='portfolio-layout';
    $('lifetimeSummary').innerHTML=`<div class="result-hero"><div class="hero-label"><span>Combined portfolio result</span><span class="subtle-pill">All recorded history</span></div><div class="hero-number ${color(net)}">${signed(net)}</div><p class="hero-explanation">${!has?'Your story starts with your first recorded trade.':!complete?'Waiting for prices to value your open positions.':'Includes your recorded entries, rebalances and covers.'}</p><div class="cost-notice"><span class="notice-dot"></span><span>${hasCosts?'After entered costs; additional charges may remain.':'Before borrow charges and other costs not yet entered.'}</span><button class="inline-link" data-record-cost>Record costs ${icon('arrow')}</button></div><div class="hero-stats"><div><span>Open pairs</span><strong>${open.length}<small> / ${list.length} total</small></strong></div><div><span>Journal records</span><strong>${trades.length+adjustments.length}<small> entries & adjustments</small></strong></div><div><span>Costs entered</span><strong>${money(costs,2)}<small>${hasCosts?' recorded':' none recorded'}</small></strong></div></div></div>
    <div class="result-breakdown"><div class="section-kicker">HOW IT ADDS UP</div><div class="breakdown-line"><div><span class="legend-dot blue"></span><span>Realized results<small>Already sold or covered</small></span></div><strong class="${color(realized)}">${signed(realized)}</strong></div><div class="breakdown-line"><div><span class="legend-dot teal"></span><span>Open-position results<small>Gains or losses still held</small></span></div><strong class="${color(unreal)}">${signed(unreal)}</strong></div><div class="breakdown-line compact"><span>Recorded costs & income</span><strong>${signed(income-costs)}</strong></div><div class="breakdown-total"><span>Combined result</span><strong class="${color(net)}">${signed(net)}</strong></div><p>Realized results are already included above. Don’t subtract covers again.</p></div>`;
    $('lifetimeSummary').querySelector('[data-record-cost]').onclick=()=>{openActivity('adjustment');$('adjAction').value='cost';adjActionChanged();};
    $('lifetimeRows').innerHTML=has?list.map((p,i)=>`<tr><td><div class="pair-identity">${avatar(p.u,i)}<div><strong>${esc(p.u)} <span class="pair-slash">/</span> ${esc(p.e)}</strong><small>${p.closed?'Closed position':'Long underlying · short ETF'}</small></div></div></td><td class="numeric ${color(p.realized)}">${signed(p.realized)}</td><td class="numeric ${color(p.unreal)}">${signed(p.unreal)}</td><td class="numeric">${money(p.costs,2)}</td><td class="numeric">${money(p.income,2)}</td><td class="numeric result-cell"><strong class="${color(p.net)}">${signed(p.net)}</strong><div class="contribution-track"><span class="${p.net<0?'loss':''}" style="width:${Number.isFinite(p.net)?Math.abs(p.net)/max*100:0}%"></span></div><small>${p.closed?'Closed':p.prices?.failed?'Refresh failed · last valid price':p.prices?esc(p.prices.source)+' · '+fmtET(p.prices.ts):'Awaiting prices'}</small></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty-state">'+icon('positions')+'<strong>No trades recorded yet</strong><p>Record your first paired entry or import an existing backup.</p><button class="secondary" id="emptyImport">Import a backup</button></div></td></tr>';
    if($('emptyImport'))$('emptyImport').onclick=()=>location.hash='backup';
    $('navPositionCount').textContent=open.length;
  };
  renderDecision=function(){
    const list=allLedgers();
    $('decisionCenter').className='watch-grid';
    $('decisionCenter').innerHTML=list.length?list.map((a,i)=>{const d=decision(a),adj=d.adj,ratio=adj?.ratio,pr=a.prices,status=d.cls==='hold'?'Balanced':d.cls==='risk'?'Needs attention':d.cls==='check'?'Review inputs':'Review',rate=parseFloat(gb(a.e)),bar=Number.isFinite(ratio)?Math.max(2,Math.min(98,50+(ratio-100)*1.5)):50;return`<article class="watch-card"><div class="watch-header"><div class="pair-identity">${avatar(a.u,i)}<div><strong>${esc(a.u)} <span class="pair-slash">/</span> ${esc(a.e)}</strong><small>${a.L}× paired strategy</small></div></div><span class="status-pill ${d.cls}">${status}</span></div><div class="watch-result"><span>Combined result</span><strong class="${color(a.net)}">${signed(a.net)}</strong></div><div class="hedge-caption"><span>Hedge balance</span><strong>${Number.isFinite(ratio)?pct(ratio):'—'} <small>/ 100% target</small></strong></div><div class="hedge-track" role="img" aria-label="Hedge balance ${Number.isFinite(ratio)?pct(ratio):'unavailable'}; target 100 percent"><span class="hedge-zone"></span><i></i>${Number.isFinite(ratio)?`<b style="left:${bar}%" class="${d.cls}"></b>`:''}</div><div class="watch-facts"><span>Borrow <strong>${pct(rate,2)}</strong></span><span>${pr?.failed?'Refresh failed':pr?esc(pr.source):'Awaiting quotes'}</span></div><details class="watch-detail"><summary><span class="status-dot ${d.cls}"></span>${esc(d.label)}<span class="detail-chevron">⌄</span></summary><p>${esc(d.reason)}</p><p>${esc(d.bs.text)}</p><p><strong>${esc(d.arb.label)}:</strong> ${esc(d.arb.text)}</p><p class="small">Long ${a.longQty.toLocaleString()} ${esc(a.u)} · Short ${a.shortQty.toLocaleString()} ${esc(a.e)}<br>Quote as of ${pr?fmtET(pr.ts):'unavailable'}</p><button class="secondary" data-snapshot="${esc(a.e)}">Update broker inputs ${icon('arrow')}</button></details></article>`;}).join(''):'<div class="empty-state"><strong>Your positions will appear here</strong><p>Add an entry to monitor hedge balance and borrowing conditions.</p></div>';
    $('decisionCenter').querySelectorAll('[data-snapshot]').forEach(b=>b.onclick=()=>{location.hash='positions';$('snapPair').value=b.dataset.snapshot;setTimeout(()=>$('snapETF').focus(),0);});
  };
  function filterScreen(){const query=$('screenSearch').value.trim().toUpperCase(),filter=$('screenFilter').value,held=filter==='held',holding=new Set(allLedgers().map(p=>p.e));let count=0;for(const tr of $('rows').children){const name=tr.querySelector('td b')?.textContent||'',ticker=name.split('/')[0].trim();tr.hidden=!!query&&!name.toUpperCase().includes(query)||held&&!holding.has(ticker)||filter==='research'&&!RESEARCH_PAIRS.has(ticker)||filter==='priority'&&!PRIORITY_PAIRS.has(ticker)||filter==='watch'&&!PAIRS.find(p=>p.e===ticker)?.watchOnly;if(!tr.hidden)count++;}$('screenResultCount').textContent=count+' pairs';}
  $('screenSearch').oninput=filterScreen;$('screenFilter').onchange=filterScreen;
  function filterJournal(){const q=$('journalSearch').value.trim().toLowerCase();for(const id of ['lots','adjustments'])for(const tr of $(id).children)tr.hidden=!!q&&!tr.textContent.toLowerCase().includes(q);}
  $('journalSearch').oninput=filterJournal;
  const originalScreen=renderScreen;renderScreen=function(){originalScreen();filterScreen();};
  const originalJournal=renderJournal;renderJournal=function(){originalJournal();filterJournal();};
  const originalMarket=renderMarketBar;renderMarketBar=function(){originalMarket();const values=Object.values(R),failed=values.filter(r=>r.err||r.failed).length,loaded=values.filter(r=>r.oldestTs),stale=loaded.some(r=>freshClass(r.oldestTs).cls==='stale');$('headerQuoteStatus').classList.toggle('attention',failed>0||stale);$('headerQuoteStatus').innerHTML='<i></i>'+ (refreshRunning?'Refreshing quotes':!loaded.length?'Quotes unavailable':failed?failed+' pairs need refresh':stale?'Quotes need review':'Quotes updated');$('headerQuoteStatus').title=loaded.length?'Oldest quote: '+fmtET(Math.min(...loaded.map(r=>r.oldestTs))):'No current quotes';document.querySelectorAll('.refresh-button').forEach(b=>b.classList.toggle('refreshing',refreshRunning));};
  const originalSave=saveState;saveState=async function(next,label){const saved=await originalSave(next,label);if(saved){if(label!=='Saved daily performance observation'){$('workspaceToast').textContent=label+' · Saved';$('workspaceToast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('workspaceToast').hidden=true,4200);}if($('activityDialog').open&&/Added entry|Corrected entry|Recorded /.test(label))$('activityDialog').close();}return saved;};
  const cloudObserver=new MutationObserver(()=>{const text=$('cloudStatus').textContent,verified=text.includes('saved and read back successfully');$('sidebarBackupTitle').textContent=verified?'Cloud backup verified':text.includes('failed')||text.includes('attention')?'Backup needs attention':'Protect your journal';$('sidebarBackupText').textContent=verified?'Encrypted recovery copy saved':'Review backup status';});cloudObserver.observe($('cloudStatus'),{childList:true,characterData:true,subtree:true});
  document.querySelectorAll('#screen th.sort').forEach(th=>{th.tabIndex=0;th.setAttribute('role','button');th.setAttribute('aria-label','Sort by '+th.textContent);th.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();th.click();}};});
  switchPage();renderAll();
})();
